"""adding phone_number column to users table

Revision ID: 4ae65bb59736
Revises: 930833894d64
Create Date: 2022-12-11 23:10:59.929000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae65bb59736'
down_revision = '930833894d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numer', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_numer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_numer')
    # ### end Alembic commands ###
